// AUTO GENERATED
//     This code was generated by signalgo add refenreces.
//     Runtime Version : 4.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     to download signalgo vsix for visual studio go https://marketplace.visualstudio.com/items?itemName=AliVisualStudio.SignalGoExtension
//     support and use signalgo go https://github.com/SignalGo/SignalGo-full-net
// AUTO GENERATED

    abstract class HelloCallbackClientServiceCallbackServiceBase { 
static String name = "hellocallbackclientservice";
         void receivedMessageAsync(String name, String family);
    }
