// <auto-generated>
//     This code was generated by signalgo add refenreces.
//     Runtime Version : 3.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     to download signalgo vsix for visual studio go https://marketplace.visualstudio.com/items?itemName=AliVisualStudio.SignalGoExtension
//     support and use signalgo go https://github.com/SignalGo/SignalGo-full-net
// </auto-generated>
import { Injectable } from '@angular/core';
import { ServerConnectionService } from './server-connection.service';
import { SignalgoAngularTest } from './Reference';
@Injectable({
  providedIn: 'root'
})
    export class HelloworldService {
        constructor(private server: ServerConnectionService) { }
        Login(yourName: string): Promise<string> {
return this.server.post<string>('Helloworld/Login', {
                        yourName:yourName
                });
        }

        GetUserInfoes(): Promise<SignalgoAngularTest.SignalGoServerExample.Models.UserInfo[]> {
return this.server.post<SignalgoAngularTest.SignalGoServerExample.Models.UserInfo[]>('Helloworld/GetUserInfoes',null
);
        }

    }
