// <auto-generated>
//     This code was generated by signalgo add refenreces.
//     Runtime Version : 3.1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     to download signalgo vsix for visual studio go https://marketplace.visualstudio.com/items?itemName=AliVisualStudio.SignalGoExtension
//     support and use signalgo go https://github.com/SignalGo/SignalGo-full-net
// </auto-generated>
export module SignalgoAngularTest {

export namespace SignalGoServerExample.Models {
    export class UserInfo{
        Id: number;

        Name: string;

        Age: number;

        Books: SignalGoServerExample.Models.BookInfo[];


    }

    export class BookInfo{
        Id: number;

        Details: string;

        UserInfo: SignalGoServerExample.Models.UserInfo;


    }

}

}
